// export { Languages as LanguagesContent } from "./Languages"
export { Chart as ChartWakatime } from "./Chart"
export { Stats as StatsContent } from "./Stats"
export { Profile as ProfileContent } from "./Profile"
export { Wakatime as WakatimeContent } from "./Wakatime"
